# Generated by Django 3.0.4 on 2020-03-26 18:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='evento',
            old_name='momentoFin',
            new_name='fecha',
        ),
        migrations.RemoveField(
            model_name='evento',
            name='momentoInicio',
        ),
    ]
