# Generated by Django 3.0.4 on 2020-04-07 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraccion',
            name='despripcion',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
