# Generated by Django 3.0.4 on 2020-04-16 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='contraccion',
            name='duración',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
        migrations.AlterField(
            model_name='contraccion',
            name='intervalo',
            field=models.DecimalField(decimal_places=2, max_digits=10),
        ),
    ]
