# Generated by Django 3.0.4 on 2020-03-17 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='fechaNacimiento',
            field=models.DateField(),
        ),
    ]
