# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0003_calendario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fecha',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=25)),
                ('momentoInicio', models.DateTimeField()),
                ('momentoFin', models.DateTimeField()),
                ('calendario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Calendario')),
            ],
        ),
    ]
