# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0004_fecha'),
    ]

    operations = [
        migrations.CreateModel(
            name='Diario',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('mama', models.OneToOneField(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Mama')),
            ],
        ),
    ]
