# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0005_diario'),
    ]

    operations = [
        migrations.CreateModel(
            name='Fotografia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('enlace', models.CharField(max_length=1000)),
                ('despription', models.CharField(blank=True, max_length=1000, null=True)),
                ('diario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Medida',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('dBiparieta', models.IntegerField()),
                ('cAbdominal', models.IntegerField()),
                ('lFemur', models.IntegerField()),
                ('diario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario')),
            ],
        ),
    ]
