# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0006_fotografia_medida'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contraccion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField()),
                ('despription', models.CharField(max_length=1000, null=True)),
                ('diario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Medicacion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('medicamento', models.CharField(max_length=50)),
                ('fechaInicio', models.DateField()),
                ('fechaFin', models.DateField()),
                ('frecuencia', models.IntegerField()),
                ('diario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Patada',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField()),
                ('despription', models.CharField(blank=True, max_length=1000, null=True)),
                ('diario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Peso',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField()),
                ('peso', models.DecimalField(decimal_places=2, max_digits=5)),
                ('tipo', models.CharField(choices=[('Madre', 'Madre'), ('Bebe', 'Bebe')], max_length=100)),
                ('diario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario')),
            ],
        ),
        migrations.CreateModel(
            name='Tension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('momento', models.DateTimeField()),
                ('tSistolica', models.DecimalField(decimal_places=2, max_digits=4)),
                ('tDiastolica', models.DecimalField(decimal_places=2, max_digits=4)),
                ('diario', models.ForeignKey(editable=False, on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario')),
            ],
        ),
    ]
