# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-20 11:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_contraccion_medicacion_patada_peso_tension'),
    ]

    operations = [
        migrations.AddField(
            model_name='calendario',
            name='nombre',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
        migrations.AddField(
            model_name='diario',
            name='nombre',
            field=models.CharField(default='SOME STRING', max_length=25),
        ),
    ]
