# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-09 20:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0007_contraccion_medicacion_patada_peso_tension'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Alumno',
        ),
    ]
