# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-20 11:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0009_auto_20200220_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='mama',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Mama'),
        ),
    ]
