# -*- coding: utf-8 -*-
# Generated by Django 1.11.27 on 2020-02-20 11:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Gestion', '0010_auto_20200220_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='calendario',
            name='mama',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Mama'),
        ),
        migrations.AlterField(
            model_name='contraccion',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario'),
        ),
        migrations.AlterField(
            model_name='diario',
            name='mama',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Mama'),
        ),
        migrations.AlterField(
            model_name='fecha',
            name='calendario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Calendario'),
        ),
        migrations.AlterField(
            model_name='fotografia',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario'),
        ),
        migrations.AlterField(
            model_name='medicacion',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario'),
        ),
        migrations.AlterField(
            model_name='medida',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario'),
        ),
        migrations.AlterField(
            model_name='patada',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario'),
        ),
        migrations.AlterField(
            model_name='peso',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario'),
        ),
        migrations.AlterField(
            model_name='tension',
            name='diario',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='Gestion.Diario'),
        ),
    ]
